### ISSUE TITLE
Update WorldCover Search to Return LULC Raster

### ISSUE THREAD

**Issue by Jack-Hayes** [uw-cryo/coincident#23]
Update `coincident.search.search(dataset='worldcover')` to return 2021 LULC of the bbox of an input geometry (GeoDataFrame or GeoSeries). Maybe returned clipped raster and print distribution statistics too?

Building off of code below:
```python
catalog = pystac_client.Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
    modifier=planetary_computer.sign_inplace,
)
search = catalog.search(collections=["esa-worldcover"], 
                            bbox=bbox)
items = search.item_collection()
```

**Comment by scottyhq** [comment]
To get the raster I suggest converting from the geodataframe back to pystac items to pass to [odc-stac](https://odc-stac.readthedocs.io/en/latest/_api/odc.stac.load.html):

```python
items = coincident.search.stac.to_pystac_items(gf)
ds = odc.stac.load(
    items,
    bbox=search_bbox,
)
```

I might open an issue on odc-stac to accept the geodataframe/stac-geoparquet directly (I think the to_pystac_items could be avoided since all the information is already in memory)!

**Comment by scottyhq** [comment]
Some enhancements in GDAL will also streamline this sort of workflow! https://github.com/OSGeo/gdal/issues/11317
